#!/bin/bash
# Extract translatable strings from Python source files
xgettext --language=Python --keyword=_ --keyword=N_ --output=webapp-manager.pot \
    usr/lib/webapp-manager/*.py \
    usr/bin/webapp-manager
